#!/bin/bash
cd /home/daniel/git/Fedora/;
# dnf -y install lorax pykickstart;
sudo setenforce 0;
# ksflatten --config fedora-livemedia.ks -o fedora-livemedia_flat.ks --version F35
mkdir -p /media/RAM
mkdir -p /media/SSD/tmp
# mount -t tmpfs -o size=28G RAM /media/RAM/
systemd-inhibit --why "Creation of Prodora" livemedia-creator --make-iso --no-virt --ks=fedora-livemedia_flat.ks --tmp /media/SSD/tmp --resultdir /media/RAM/ISO --project "Prodora" --releasever 35 --volid "Prodora 35"; 
